export const keywords = [
  "Alexandru Şerban",
  "jonny",
  "alexjonny",
  "jonnyalex",
  "jonny alex",
  "serban",
  "serban alexandru",
  "alexandru serban",
  "serban alex",
  "alex serban",
  "serban alexandru jonny",
  "jonny serban alexandru",
  "alex jonny",
  "front-end developer",
  "front-end",
  "frontend",
  "developer",
  "javascript",
  "typescript",
  "react",
  "nextjs",
  "css",
  "html",
  "web development",
  "web developer",
  "web",
  "development",
  "design",
  "ui",
  "ux",
  "ui/ux",
  "Next.js",
  "ReactJs",
  "React.js",
  "nodejs",
  "node.js",
  "node",
  "framework",
  "website",
  "programming",
  "code",
  "coder",
  "coding",
  "software engineer",
  "software developer",
  "fullstack",
  "full-stack",
  "full stack",
  "fullstack developer",
  "full-stack developer",
  "software",
  "web apps",
  "SPA",
  "single page application",
];
